[project]
name = "jaxqkv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flax>=0.8.5",
    "jax>=0.4.30",
    "optax>=0.2.4",
]
