[project]
name = "jaxqkv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flax>=0.8.5",
    "huggingface-hub>=0.29.0",
    "jax>=0.4.30",
    "matplotlib>=3.9.4",
    "optax>=0.2.4",
    "tiktoken>=0.9.0",
]
